import type { ToolCopyDef } from "@/lib/lite/copy-base";
import type { Locale } from "@/lib/locale";

/**
 * Number format. A spreadsheet in, the chosen columns out in one number
 * format. The search it answers in Spanish is the everyday LatAm one: a file
 * exported with "1.234,56" that Excel reads as text, or the other way round.
 */
const numberFormat: Record<Locale, ToolCopyDef> = {
  es: {
    vocab: {
      doc: "hoja de cálculo",
      docs: "hojas de cálculo",
      a_doc: "una hoja de cálculo",
      the_doc: "la hoja de cálculo",
      the_docs: "las hojas de cálculo",
      your_doc: "tu hoja de cálculo",
      your_docs: "tus hojas de cálculo",
      all_your_docs: "todas tus hojas de cálculo",
      all_docs: "todas las hojas de cálculo",
      each_doc: "cada hoja de cálculo",
      another_doc: "otra hoja de cálculo",
      this_doc: "esta hoja de cálculo",
    },
    overrides: {
      title: "Convertir comas a puntos en Excel, gratis",
      description:
        "Sube un Excel o CSV con números como 1.234,56 o 1,234.56 y recíbelos en un solo formato, listos para sumar. Eliges las columnas y el formato. Gratis, sin registro para ver el resultado.",
      label: "Comas y puntos en números",
      h1: "Convierte comas a puntos en tus números",
      intro:
        "Sube el Excel o el CSV. Eliges qué columnas son números y cómo quieres que queden: 1234.56, 1,234.56 o 1.234,56. Tavnit los convierte todos y te devuelve tu archivo, con las mismas columnas y en el mismo orden.",
      trust: ["CSV o Excel · hasta 500 filas", "{limit} archivos gratis al día", "Se borra todo a las 24 h"],
      drop: {
        title: "Arrastra tu Excel o CSV aquí",
        hint: "o elige un archivo de tu computadora",
        choose: "Elegir archivo",
        sample: "Probar con un archivo de ejemplo",
        formats: "CSV o .xlsx · hasta 4 MB y 500 filas",
      },
      errors: {
        unsupported: "Solo aceptamos archivos CSV o Excel (.xlsx).",
        xls: "Es un Excel antiguo (.xls). Ábrelo en Excel y guárdalo como .xlsx o .csv.",
        too_many_rows: "La versión gratis procesa hasta 500 filas. Sube una parte del archivo.",
        too_many_columns: "Elige hasta 10 columnas a la vez.",
        no_columns: "Elige al menos una columna.",
        nothing_to_clean: "En esas columnas no encontramos números que convertir.",
        empty: "El archivo está vacío o no tiene filas debajo del encabezado.",
        unreadable: "No pudimos leer el archivo. Si es un Excel, guárdalo de nuevo como .xlsx.",
        failed: "No pudimos convertir este archivo. Prueba de nuevo o con el archivo de ejemplo.",
      },
      how: {
        heading: "Cómo funciona",
        steps: [
          { title: "Sube el archivo", body: "Un CSV o un Excel. Da igual si viene separado por comas o por punto y coma." },
          { title: "Elige columnas y formato", body: "Marcamos las columnas que parecen números. Dices si tus decimales van con coma o con punto, y cómo los quieres." },
          { title: "Revisa y descarga", body: "Ves las celdas que cambiaron resaltadas. Con tu cuenta gratis te llevas el archivo en Excel o CSV." },
        ],
      },
      faqs: [
        { q: "¿Por qué Excel no suma mis números?", a: "Porque los está leyendo como texto. Pasa cuando el archivo viene de un sistema o de un país que escribe los decimales distinto al tuyo: 1.234,56 en un Excel configurado para 1,234.56, o al revés. Convertirlos a un solo formato los vuelve números otra vez." },
        { q: "¿Cómo sabe si mis decimales van con coma o con punto?", a: "Lo adivinamos mirando tus valores: si aparece 1.234,56, el decimal es la coma. Si no se puede saber, por ejemplo con 1.234 solo, eliges tú. Esa elección decide cómo se lee cada número." },
        { q: "¿Qué formato me conviene?", a: "1234.56, sin separador de miles, es el que cualquier sistema, fórmula o importación lee sin problemas. 1,234.56 y 1.234,56 son para mostrar el archivo a personas, según tu país." },
        { q: "¿Qué pasa con las celdas que no son números?", a: "Se quedan como estaban. Un porcentaje (15%), un texto (N/A) o una celda vacía no se tocan: solo cambia lo que es claramente un número." },
        { q: "¿Qué formatos acepta?", a: "CSV separado por comas, punto y coma o tabulador, y Excel .xlsx, de hasta 4 MB y 500 filas. Si tienes un Excel antiguo (.xls), guárdalo como .xlsx." },
        { q: "¿Qué pasa con mi archivo?", a: "Se usa solo para esta conversión y se borra a las 24 horas, junto con el resultado. Solo tu navegador puede ver el resultado." },
        { q: "¿Cómo hago que esto pase solo?", a: "En Tavnit, la misma regla es un Cleaner: se aplica sola a cada documento que extraes o a cada archivo que llega por correo o API, junto con fechas, monedas y validaciones." },
      ],
      clean: {
        setup: {
          heading: "Elige las columnas y el formato",
          fileSummary: "{rows} · {cols}",
          columnsLabel: "Columnas con números",
          columnsHint: "Hasta {max}. Marcamos las que parecen números.",
          tooMany: "Puedes elegir hasta {max} columnas a la vez.",
          inputLabel: "En tu archivo, los decimales van con",
          inputOptions: { comma: "coma · 1.234,56", dot: "punto · 1,234.56" },
          outputLabel: "Quiero los números así",
          outputOptions: { plain: "1234.56 · para fórmulas y sistemas", us: "1,234.56", latam: "1.234,56" },
          preview: "Primeras filas",
          run: "Convertir",
          change: "Cambiar archivo",
        },
        stages: ["Subiendo el archivo", "Leyendo las columnas", "Convirtiendo los números", "Armando tu archivo"],
        heading: "Listo: {file}",
        summary: "{cells} cambiadas en {cols}",
        cellWord: ["celda", "celdas"],
        columnWord: ["columna", "columnas"],
        unchanged: "No hizo falta cambiar ninguna celda: ya estaban en ese formato.",
        highlight: "En azul, las celdas que cambiaron.",
        shown: "Se muestran {shown} de {total} filas. La descarga incluye todas.",
        downloadXlsx: "Descargar Excel",
        downloadCsv: "Descargar CSV",
        another: "Convertir otro archivo",
        automate: {
          heading: "Que pase solo, con cada archivo",
          body: "En Tavnit esta regla es un Cleaner. Lo armas una vez y se aplica solo a cada factura que extraes o a cada archivo que llega por correo o API, junto con fechas, monedas y validaciones.",
          cta: "Crear cuenta gratis",
          docs: "Qué es un Cleaner",
        },
      },
    },
  },
  en: {
    vocab: {
      doc: "spreadsheet",
      docs: "spreadsheets",
      a_doc: "a spreadsheet",
      the_doc: "the spreadsheet",
      the_docs: "the spreadsheets",
      your_doc: "your spreadsheet",
      your_docs: "your spreadsheets",
      all_your_docs: "all your spreadsheets",
      all_docs: "all spreadsheets",
      each_doc: "every spreadsheet",
      another_doc: "another spreadsheet",
      this_doc: "this spreadsheet",
    },
    overrides: {
      title: "Fix Number Format in Excel or CSV, Free",
      description:
        "Upload an Excel or CSV file with numbers like 1.234,56 or 1,234.56 and get them back in one format, ready to add up. You pick the columns and the format. Free, no sign-up to see the result.",
      label: "Fix number format",
      h1: "Fix the number format in your spreadsheet",
      intro:
        "Upload the Excel or CSV file. Pick which columns hold numbers and how you want them: 1234.56, 1,234.56 or 1.234,56. Tavnit converts every one and hands your file back with the same columns in the same order.",
      trust: ["CSV or Excel · up to 500 rows", "{limit} free files a day", "Everything is deleted after 24 h"],
      drop: {
        title: "Drop your Excel or CSV file here",
        hint: "or choose a file from your computer",
        choose: "Choose file",
        sample: "Try a sample file",
        formats: "CSV or .xlsx · up to 4 MB and 500 rows",
      },
      errors: {
        unsupported: "Only CSV or Excel (.xlsx) files.",
        xls: "This is an old Excel file (.xls). Open it in Excel and save it as .xlsx or .csv.",
        too_many_rows: "The free version handles up to 500 rows. Upload part of the file.",
        too_many_columns: "Pick up to 10 columns at a time.",
        no_columns: "Pick at least one column.",
        nothing_to_clean: "We found no numbers to convert in those columns.",
        empty: "The file is empty or has no rows under the header.",
        unreadable: "We could not read the file. If it is an Excel file, save it again as .xlsx.",
        failed: "We could not convert this file. Try again, or try the sample file.",
      },
      how: {
        heading: "How it works",
        steps: [
          { title: "Upload the file", body: "A CSV or an Excel file, comma or semicolon separated." },
          { title: "Pick columns and format", body: "We tick the columns that look like numbers. You say whether your decimals use a comma or a point, and how you want them." },
          { title: "Review and download", body: "The cells that changed are highlighted. With your free account you take the file as Excel or CSV." },
        ],
      },
      faqs: [
        { q: "Why won't Excel add up my numbers?", a: "Because it reads them as text. It happens when the file comes from a system or a country that writes decimals differently from yours: 1.234,56 in an Excel set up for 1,234.56, or the reverse. Putting them in one format makes them numbers again." },
        { q: "How do you know whether my decimals use a comma or a point?", a: "We guess from your values: if 1.234,56 appears, the decimal is the comma. When it cannot be told, 1.234 on its own for instance, you choose. That choice decides how every number is read." },
        { q: "Which format should I pick?", a: "1234.56, with no thousands separator, is the one every system, formula and import reads without trouble. 1,234.56 and 1.234,56 are for showing the file to people, depending on your country." },
        { q: "What happens to cells that are not numbers?", a: "They stay as they were. A percentage (15%), text (N/A) or an empty cell is left alone: only what is clearly a number changes." },
        { q: "What formats does it accept?", a: "CSV separated by commas, semicolons or tabs, and Excel .xlsx, up to 4 MB and 500 rows. If you have an old Excel file (.xls), save it as .xlsx." },
        { q: "What happens to my file?", a: "It is used only for this conversion and deleted after 24 hours along with the result. Only your browser can see the result." },
        { q: "How do I make this happen on its own?", a: "In Tavnit the same rule is a Cleaner: it runs by itself on every document you extract or every file that arrives by email or API, alongside dates, currencies and checks." },
      ],
      clean: {
        setup: {
          heading: "Pick the columns and the format",
          fileSummary: "{rows} · {cols}",
          columnsLabel: "Columns with numbers",
          columnsHint: "Up to {max}. We ticked the ones that look like numbers.",
          tooMany: "You can pick up to {max} columns at a time.",
          inputLabel: "In your file, decimals use a",
          inputOptions: { comma: "comma · 1.234,56", dot: "point · 1,234.56" },
          outputLabel: "I want the numbers as",
          outputOptions: { plain: "1234.56 · for formulas and systems", us: "1,234.56", latam: "1.234,56" },
          preview: "First rows",
          run: "Convert",
          change: "Change file",
        },
        stages: ["Uploading the file", "Reading the columns", "Converting the numbers", "Building your file"],
        heading: "Done: {file}",
        summary: "{cells} changed in {cols}",
        cellWord: ["cell", "cells"],
        columnWord: ["column", "columns"],
        unchanged: "No cell needed changing: they were already in that format.",
        highlight: "The cells that changed are in blue.",
        shown: "Showing {shown} of {total} rows. The download has all of them.",
        downloadXlsx: "Download Excel",
        downloadCsv: "Download CSV",
        another: "Convert another file",
        automate: {
          heading: "Make it happen with every file",
          body: "In Tavnit this rule is a Cleaner. You set it up once and it runs by itself on every invoice you extract or every file that arrives by email or API, alongside dates, currencies and checks.",
          cta: "Create a free account",
          docs: "What is a Cleaner",
        },
      },
    },
  },
};

export default numberFormat;
